services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gsb_app
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
    networks:
      - app_network
    depends_on:
      - db
    # Option: attendre la DB puis exécuter le script avant de lancer php-fpm
    command: sh -c "cd /var/www/html/bin/gendatas && php majGSB.php && php-fpm"


  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80
      - 443
    networks:
      - app_network
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gsb_frais
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_server
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - db
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  nginx-config: {}
  nginx-html: {}
  db_data: